version: '3.7'
services:
  interlink:
    image:  ghcr.io/dodas-ts/interlink:v2
    restart: always
    expose:
    - 3000:3000
    ports:
    - 3000:3000
    volumes:
    - type: bind
      source: ./config
      target: /etc/interlink
    # healthcheck:
    #   test: ["CMD", "/wn-check.sh"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 5s
  interlink-plugin:
    image: ghcr.io/dodas-ts/intertwin-plugin:docker-v5
    restart: always
    privileged: true
    expose:
    - 4000:4000
    ports:
    - 4000:4000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock 
    # healthcheck:
    #   test: ["CMD", "/wn-check.sh"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 5s
