apiVersion: v1
kind: Pod
metadata:
  name: testvk
spec:
  restartPolicy: OnFailure 
  containers:
  - image: busybox
    command:
      - sleep
      - infinity 
    imagePullPolicy: Always
    name: busyecho
  dnsPolicy: ClusterFirst
  nodeSelector:
    kubernetes.io/role: agent
    beta.kubernetes.io/os: linux
    type: virtual-kubelet
    kubernetes.io/hostname: mock-vk
  tolerations:
  - key: virtual-kubelet.io/provider
    operator: Exists
